package gitscan

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"testing"
)

// tinyPNG returns a valid 1x1 PNG with the given color seed.
// The seed simply alters one byte in the IDAT so the SHAs differ.
func tinyPNG(seed byte) []byte {
	// 1x1 PNG, single-pixel RGBA, generated by hand.
	// We build a small image programmatically to keep this self-contained.
	// Header: PNG signature.
	sig := []byte{0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a}
	// Use a small palette PNG to avoid checksum complexity: easier to
	// just embed two distinct precomputed PNGs.
	_ = sig
	if seed%2 == 0 {
		return mustDecodeHex("89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c4890000000d49444154789c63f8cf0000000300010050cdfdda0000000049454e44ae426082")
	}
	return mustDecodeHex("89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c4890000000d49444154789c63f8ff3f00050001016a55e8200000000049454e44ae426082")
}

func mustDecodeHex(s string) []byte {
	out := make([]byte, len(s)/2)
	for i := 0; i < len(out); i++ {
		hi := hexDigit(s[2*i])
		lo := hexDigit(s[2*i+1])
		out[i] = (hi << 4) | lo
	}
	return out
}

func hexDigit(b byte) byte {
	switch {
	case b >= '0' && b <= '9':
		return b - '0'
	case b >= 'a' && b <= 'f':
		return b - 'a' + 10
	case b >= 'A' && b <= 'F':
		return b - 'A' + 10
	}
	panic("bad hex")
}

// initRepo creates a temp git repo, sets identity, and returns its path.
func initRepo(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	for _, args := range [][]string{
		{"init", "-q", "-b", "main"},
		{"config", "user.email", "test@example.com"},
		{"config", "user.name", "Test"},
		{"config", "commit.gpgsign", "false"},
	} {
		cmd := exec.Command("git", args...)
		cmd.Dir = dir
		if out, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("git %v: %v\n%s", args, err, out)
		}
	}
	return dir
}

func writeFile(t *testing.T, dir, rel string, body []byte) {
	t.Helper()
	full := filepath.Join(dir, rel)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(full, body, 0o644); err != nil {
		t.Fatalf("write %s: %v", full, err)
	}
}

func gitDo(t *testing.T, dir string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("git %v: %v\n%s", args, err, out)
	}
}

func commitAll(t *testing.T, dir, msg string) {
	t.Helper()
	gitDo(t, dir, "add", "-A")
	gitDo(t, dir, "commit", "-q", "-m", msg)
}

func defaultScanner(repo string) *Scanner {
	return &Scanner{
		RepoDir:   repo,
		BaseRef:   "HEAD",
		Globs:     []string{"**/__Snapshots__/*.png"},
		AxisRegex: regexp.MustCompile(`(?P<test>[^/_]+)__(?P<device>[^/_]+)__(?P<theme>[^/.]+)\.png`),
	}
}

func TestScan_emptyRepoNoDiffs(t *testing.T) {
	repo := initRepo(t)
	writeFile(t, repo, "README.md", []byte("hi"))
	commitAll(t, repo, "init")

	diffs, _, err := defaultScanner(repo).Scan(context.Background())
	if err != nil {
		t.Fatalf("Scan: %v", err)
	}
	if len(diffs) != 0 {
		t.Errorf("expected 0 diffs, got %d", len(diffs))
	}
}

func TestScan_modifiedSnapshot(t *testing.T) {
	repo := initRepo(t)
	writeFile(t, repo, "ios/__Snapshots__/Foo__iphone17__dark.png", tinyPNG(0))
	commitAll(t, repo, "baseline")
	writeFile(t, repo, "ios/__Snapshots__/Foo__iphone17__dark.png", tinyPNG(1))

	diffs, warnings, err := defaultScanner(repo).Scan(context.Background())
	if err != nil {
		t.Fatalf("Scan: %v", err)
	}
	if len(warnings) != 0 {
		t.Errorf("unexpected warnings: %v", warnings)
	}
	if len(diffs) != 1 {
		t.Fatalf("expected 1 diff, got %d", len(diffs))
	}
	d := diffs[0]
	if d.Status != StatusModified {
		t.Errorf("Status = %v, want Modified", d.Status)
	}
	if d.Path != "ios/__Snapshots__/Foo__iphone17__dark.png" {
		t.Errorf("Path = %q", d.Path)
	}
	if len(d.Baseline) == 0 {
		t.Error("Baseline empty")
	}
	if len(d.Current) == 0 {
		t.Error("Current empty")
	}
	if d.Axes["test"] != "Foo" || d.Axes["device"] != "iphone17" || d.Axes["theme"] != "dark" {
		t.Errorf("Axes = %v", d.Axes)
	}
}

func TestScan_addedUntrackedSnapshot(t *testing.T) {
	repo := initRepo(t)
	writeFile(t, repo, "README.md", []byte("hi"))
	commitAll(t, repo, "init")
	writeFile(t, repo, "ios/__Snapshots__/New__iphone17__light.png", tinyPNG(0))

	diffs, _, err := defaultScanner(repo).Scan(context.Background())
	if err != nil {
		t.Fatalf("Scan: %v", err)
	}
	if len(diffs) != 1 {
		t.Fatalf("expected 1 diff, got %d", len(diffs))
	}
	d := diffs[0]
	if d.Status != StatusAdded {
		t.Errorf("Status = %v, want Added", d.Status)
	}
	if len(d.Baseline) != 0 {
		t.Errorf("Baseline should be empty for Added, got %d bytes", len(d.Baseline))
	}
	if len(d.Current) == 0 {
		t.Error("Current empty")
	}
}

func TestScan_deletedSnapshot(t *testing.T) {
	repo := initRepo(t)
	writeFile(t, repo, "ios/__Snapshots__/Gone__iphone17__dark.png", tinyPNG(0))
	commitAll(t, repo, "baseline")
	if err := os.Remove(filepath.Join(repo, "ios/__Snapshots__/Gone__iphone17__dark.png")); err != nil {
		t.Fatal(err)
	}

	diffs, _, err := defaultScanner(repo).Scan(context.Background())
	if err != nil {
		t.Fatalf("Scan: %v", err)
	}
	if len(diffs) != 1 {
		t.Fatalf("expected 1 diff, got %d", len(diffs))
	}
	d := diffs[0]
	if d.Status != StatusDeleted {
		t.Errorf("Status = %v, want Deleted", d.Status)
	}
	if len(d.Baseline) == 0 {
		t.Error("Baseline empty (should have HEAD content)")
	}
	if len(d.Current) != 0 {
		t.Errorf("Current should be empty for Deleted, got %d bytes", len(d.Current))
	}
}

func TestScan_outsideGlobIgnored(t *testing.T) {
	repo := initRepo(t)
	writeFile(t, repo, "docs/diagram.png", tinyPNG(0))
	commitAll(t, repo, "baseline")
	writeFile(t, repo, "docs/diagram.png", tinyPNG(1))

	diffs, _, err := defaultScanner(repo).Scan(context.Background())
	if err != nil {
		t.Fatalf("Scan: %v", err)
	}
	if len(diffs) != 0 {
		t.Errorf("expected 0 diffs (outside glob), got %d", len(diffs))
	}
}

func TestScan_nonPNGInGlobWarnsAndSkips(t *testing.T) {
	repo := initRepo(t)
	writeFile(t, repo, "ios/__Snapshots__/notes.txt", []byte("a"))
	commitAll(t, repo, "baseline")
	writeFile(t, repo, "ios/__Snapshots__/notes.txt", []byte("b"))

	s := defaultScanner(repo)
	s.Globs = []string{"**/__Snapshots__/*"}
	diffs, warnings, err := s.Scan(context.Background())
	if err != nil {
		t.Fatalf("Scan: %v", err)
	}
	if len(diffs) != 0 {
		t.Errorf("expected 0 diffs (non-PNG), got %d", len(diffs))
	}
	if len(warnings) == 0 {
		t.Error("expected a warning about non-PNG")
	}
}

func TestScan_unparsedAxesStillIncluded(t *testing.T) {
	repo := initRepo(t)
	writeFile(t, repo, "ios/__Snapshots__/weird_name.png", tinyPNG(0))
	commitAll(t, repo, "baseline")
	writeFile(t, repo, "ios/__Snapshots__/weird_name.png", tinyPNG(1))

	diffs, _, err := defaultScanner(repo).Scan(context.Background())
	if err != nil {
		t.Fatalf("Scan: %v", err)
	}
	if len(diffs) != 1 {
		t.Fatalf("expected 1 diff, got %d", len(diffs))
	}
	if len(diffs[0].Axes) != 0 {
		t.Errorf("Axes should be empty for unparsed name, got %v", diffs[0].Axes)
	}
}

func TestScan_notAGitRepoErrors(t *testing.T) {
	dir := t.TempDir()
	_, _, err := (&Scanner{
		RepoDir:   dir,
		BaseRef:   "HEAD",
		Globs:     []string{"*.png"},
		AxisRegex: regexp.MustCompile(`(?P<x>.*)\.png`),
	}).Scan(context.Background())
	if err == nil {
		t.Fatal("expected error for non-git dir")
	}
}

func TestScan_multipleDiffsSortedByPath(t *testing.T) {
	repo := initRepo(t)
	writeFile(t, repo, "ios/__Snapshots__/B__iphone17__dark.png", tinyPNG(0))
	writeFile(t, repo, "ios/__Snapshots__/A__iphone17__dark.png", tinyPNG(0))
	commitAll(t, repo, "baseline")
	writeFile(t, repo, "ios/__Snapshots__/B__iphone17__dark.png", tinyPNG(1))
	writeFile(t, repo, "ios/__Snapshots__/A__iphone17__dark.png", tinyPNG(1))

	diffs, _, err := defaultScanner(repo).Scan(context.Background())
	if err != nil {
		t.Fatalf("Scan: %v", err)
	}
	if len(diffs) != 2 {
		t.Fatalf("expected 2 diffs, got %d", len(diffs))
	}
	paths := []string{diffs[0].Path, diffs[1].Path}
	sorted := append([]string{}, paths...)
	sort.Strings(sorted)
	if paths[0] != sorted[0] || paths[1] != sorted[1] {
		t.Errorf("diffs not sorted by path: %v", paths)
	}
}
